// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Baidu: typeof import('./src/components/icons/Baidu.vue')['default']
    BaiduIcon: typeof import('./src/components/icons/BaiduIcon.vue')['default']
    GoogleIcon: typeof import('./src/components/icons/GoogleIcon.vue')['default']
    HomeHeader: typeof import('./src/components/HomeHeader.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    Microsoft: typeof import('./src/components/icons/Microsoft.vue')['default']
    MicrosoftIcon: typeof import('./src/components/icons/MicrosoftIcon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
  }
}
